<a href="https://colab.research.google.com/github/benjadiaz112/programacion-para-ciencia-de-dato1/blob/main/guia_1_ciencia_de_dato.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
import numpy as np

#listas de datos
notas = [6.5,4.0, 7.0, 4.3, 5.7]
print(notas)
print("la primera calificacion es:", notas[0])
#diccionarios python

notas2_Estudiantes = {
    "ana": 6.5,
    "luis": 4.5,
    "benja": 5.8
}
promedio = np.mean(list(notas2_Estudiantes.values()))

print(f"El promedio es: {promedio:.2f}")
datos = {
    "nombre": ["ana", "luis", "maria", "pedro"],
    "nota": [6.5, 7.0, 4.3, 5.1]
}

df = pd.DataFrame(datos)
df_promediobajo5 = df[df["nota"] < 5]
print(df_promediobajo5)

# idxmax() encuentra la POSICIÓN (el índice) de la nota más alta
indice_maximo = df["nota"].idxmax()

# .loc usa ese índice para extraer la FILA completa
estudiante_mas_alto = df.loc[indice_maximo]

estudiante_mas_alto

[6.5, 4.0, 7.0, 4.3, 5.7]
la primera calificacion es: 6.5
El promedio es: 5.60
  nombre  nota
2  maria   4.3

nombre    luis
nota       7.0
Name: 1, dtype: object

PRACTICANDO

In [39]:
data = {
    'Producto':['Laptop', 'Mouse', 'Monitor', 'Teclado'],
    'Precio': [750000, 20000, 50000, 35000],
    'Stock':[10, 20, 15, 25]
}

In [42]:

df_productos = pd.DataFrame(data)
print("DataFrame de productos:")
print(df_productos)

DataFrame de productos:
  Producto  Precio  Stock
0   Laptop  750000     10
1    Mouse   20000     20
2  Monitor   50000     15
3  Teclado   35000     25

In [41]:


promedio_stock = np.mean(df_productos['Stock'])
print(f"El promedio de stock de los productos es: {promedio_stock:.2f}")

El promedio de stock de los productos es: 17.50

In [35]:
# 7. Filtrar los productos con un stock igual o mayor a 20.
productos_stock_mayor_igual_20 = df_productos[df_productos['Stock'] >= 20]
print("Productos con stock igual o mayor a 20:")
print(productos_stock_mayor_igual_20)

Productos con stock igual o mayor a 20:

  Producto  Precio  Stock
1    Mouse   20000     20
3  Teclado   35000     25

In [34]:
print("\n" + "*"*30 + "\n")

******************************

In [32]:
# 8. Mostrar el promedio del precio
promedio_precio = df_productos['Precio'].mean()
print(f"El promedio del precio de los productos es: {promedio_precio:.2f}")

El promedio del precio de los productos es: 213750.00

In [33]:
print("\n" + "*"*30 + "\n")

******************************

In [36]:
# 9. Mostrar la cantidad total de todos los productos (suma de stock)
cantidad_total_stock = df_productos['Stock'].sum()
print(f"La cantidad total de stock de todos los productos es: {cantidad_total_stock}")

La cantidad total de stock de todos los productos es: 70

In [38]:
print("\n" + "*"*30 + "\n")

******************************

In [37]:
# 10. Mostrar la información de los productos con precio mayor o igual a 500000
productos_precio_mayor_igual_500k = df_productos[df_productos['Precio'] >= 500000]
print("Productos con precio mayor o igual a 500000:")
print(productos_precio_mayor_igual_500k)

Productos con precio mayor o igual a 500000:

  Producto  Precio  Stock
0   Laptop  750000     10